version: '3'

services:
  earnings_ratings:
    build: Earnings-and-Ratings/
    depends_on:
      - 'earnings_ratings_db'
    links:
      - 'earnings_ratings_db'
    ports:
      - '3004:3004'

  earnings_ratings_db:
    build: Earnings-and-Ratings-DB
    image: mysql/mysql-server:latest
    environment:
      - 'MYSQL_ROOT_PASSWORD=rootpasswd'
      - 'MYSQL_DATABASE=invesTechSol_JB'
    ports:
      - '3306:3306'